export type Lesson = { slug:string; track:string; number:number; title:string; summary:string; duration:string; objectives:string[]; concept:string; code:string; practice:string; next?:string };

export const lessons: Lesson[] = [
{slug:"getting-started",track:"Foundations",number:1,title:"Meet COBOL",summary:"Write, compile, and understand your first COBOL program.",duration:"12 min",objectives:["Explain where COBOL is used","Compile a free-format program","Recognize statements and terminators"],concept:"COBOL is a compiled language designed for readable business logic and exact decimal arithmetic. Its explicit structure makes large systems easier to audit and maintain.",code:`IDENTIFICATION DIVISION.\nPROGRAM-ID. HELLO-COBOL.\nPROCEDURE DIVISION.\n    DISPLAY "Hello, mainframe."\n    STOP RUN.`,practice:"Change the greeting, compile again, and confirm the process returns code zero.",next:"program-structure"},
{slug:"program-structure",track:"Foundations",number:2,title:"Program structure",summary:"Navigate divisions, sections, paragraphs, sentences, and statements.",duration:"15 min",objectives:["Name the four divisions","Create a paragraph","Avoid accidental sentence scope"],concept:"A traditional COBOL program is organized into IDENTIFICATION, ENVIRONMENT, DATA, and PROCEDURE divisions. Only the divisions needed by a program must appear.",code:`IDENTIFICATION DIVISION.\nPROGRAM-ID. STRUCTURE-DEMO.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 WS-MESSAGE PIC X(20) VALUE "Structured and clear".\nPROCEDURE DIVISION.\nMAIN-PROCEDURE.\n    DISPLAY WS-MESSAGE\n    STOP RUN.`,practice:"Add a second paragraph named CLEAN-UP that displays a completion message.",next:"data-pic"},
{slug:"data-pic",track:"Foundations",number:3,title:"Data & PIC clauses",summary:"Describe text, numbers, signs, decimals, and edited output.",duration:"22 min",objectives:["Read common PIC strings","Choose display or computational storage","Format numeric output"],concept:"The PICTURE clause is a compact data contract. X represents alphanumeric positions, 9 numeric digits, S a sign, and V an implied decimal point.",code:`01 CUSTOMER-NAME    PIC X(30).\n01 ITEM-COUNT       PIC 9(4) VALUE ZERO.\n01 ACCOUNT-BALANCE PIC S9(7)V99 COMP-3.\n01 PRINT-BALANCE   PIC $$$,$$9.99-.`,practice:"Design fields for an eight-digit employee ID, hourly rate, and formatted paycheck.",next:"move-values"},
{slug:"move-values",track:"Foundations",number:4,title:"MOVE and initialization",summary:"Move, initialize, and transform business data safely.",duration:"18 min",objectives:["Use MOVE with literals and fields","Understand truncation","Reset groups with INITIALIZE"],concept:"MOVE copies a sending value to one or more receivers. The compiler applies category rules, alignment, and truncation based on the receiving description.",code:`MOVE "ACTIVE" TO WS-STATUS.\nMOVE WS-SUBTOTAL TO WS-TOTAL WS-AUDIT-TOTAL.\nINITIALIZE CUSTOMER-RECORD\n    REPLACING NUMERIC DATA BY ZERO.`,practice:"Move a nine-character value into PIC X(5) and predict which characters remain.",next:"arithmetic"},
{slug:"arithmetic",track:"Business logic",number:5,title:"Exact arithmetic",summary:"Use business-safe ADD, SUBTRACT, MULTIPLY, DIVIDE, and COMPUTE.",duration:"25 min",objectives:["Write rounded calculations","Handle size errors","Avoid floating-point money bugs"],concept:"COBOL decimal types and arithmetic verbs model financial rules directly. ROUNDED and ON SIZE ERROR make precision and overflow behavior explicit.",code:`COMPUTE WS-NET ROUNDED =\n    WS-GROSS - WS-TAX - WS-DEDUCTIONS\n    ON SIZE ERROR\n        MOVE "Y" TO WS-CALCULATION-ERROR\nEND-COMPUTE.`,practice:"Calculate compound interest for one year and round to the nearest cent.",next:"conditions"},
{slug:"conditions",track:"Business logic",number:6,title:"IF and conditions",summary:"Express decisions with readable conditions and explicit scope.",duration:"20 min",objectives:["Combine conditions safely","Use condition names","Terminate IF explicitly"],concept:"Conditions compare data or test named level-88 values. Prefer END-IF over period-dependent scope so later edits cannot silently change behavior.",code:`88 ACCOUNT-ACTIVE VALUE "A".\n\nIF ACCOUNT-ACTIVE AND BALANCE > ZERO\n    PERFORM CALCULATE-INTEREST\nELSE\n    MOVE "REVIEW" TO ACCOUNT-ACTION\nEND-IF.`,practice:"Add a condition that routes accounts over $10,000 to premium processing.",next:"evaluate"},
{slug:"evaluate",track:"Business logic",number:7,title:"EVALUATE",summary:"Replace tangled decision trees with COBOL's powerful case statement.",duration:"18 min",objectives:["Match values and ranges","Use EVALUATE TRUE","Handle OTHER cases"],concept:"EVALUATE can match one or several subjects, ranges, and boolean expressions. It often communicates business decision tables better than nested IF statements.",code:`EVALUATE TRUE\n    WHEN SCORE >= 90 MOVE "A" TO GRADE\n    WHEN SCORE >= 80 MOVE "B" TO GRADE\n    WHEN SCORE >= 70 MOVE "C" TO GRADE\n    WHEN OTHER       MOVE "F" TO GRADE\nEND-EVALUATE.`,practice:"Model shipping prices by destination zone and package weight.",next:"perform-loops"},
{slug:"perform-loops",track:"Business logic",number:8,title:"PERFORM and loops",summary:"Structure reusable procedures and safe iteration.",duration:"25 min",objectives:["Use inline and out-of-line PERFORM","Write TEST BEFORE and AFTER loops","Prevent runaway loops"],concept:"PERFORM executes a block or procedure. VARYING expresses counted loops while UNTIL expresses condition-driven processing.",code:`PERFORM VARYING WS-INDEX FROM 1 BY 1\n    UNTIL WS-INDEX > ITEM-COUNT\n    ADD ITEM-AMOUNT(WS-INDEX) TO ORDER-TOTAL\nEND-PERFORM.`,practice:"Loop through twelve monthly balances and calculate the annual average.",next:"strings"},
{slug:"strings",track:"Business logic",number:9,title:"Strings and text",summary:"Build, split, and inspect fixed-width business text.",duration:"28 min",objectives:["Use STRING and UNSTRING","Count or replace text with INSPECT","Handle delimiters"],concept:"STRING combines values into a destination, UNSTRING parses delimited input, and INSPECT counts or replaces characters without manual loops.",code:`STRING FIRST-NAME DELIMITED BY SPACE\n       " " DELIMITED BY SIZE\n       LAST-NAME DELIMITED BY SPACE\n  INTO DISPLAY-NAME\nEND-STRING.`,practice:"Parse a CSV line into account number, name, and balance fields.",next:"tables"},
{slug:"tables",track:"Data structures",number:10,title:"Tables and OCCURS",summary:"Model arrays, repeated groups, and variable-length data.",duration:"30 min",objectives:["Define one and two-dimensional tables","Index safely","Use OCCURS DEPENDING ON"],concept:"OCCURS repeats a field or group. Indexes are compiler-managed positions; subscripts are ordinary numeric values.",code:`01 MONTHLY-SALES.\n   05 SALES-AMOUNT PIC S9(7)V99 COMP-3\n      OCCURS 12 TIMES INDEXED BY SALES-IDX.\n\nSET SALES-IDX TO 1\nMOVE 12500.50 TO SALES-AMOUNT(SALES-IDX).`,practice:"Create a 7×24 table of hourly transaction counts by day.",next:"search-sort"},
{slug:"search-sort",track:"Data structures",number:11,title:"SEARCH and SORT",summary:"Find table entries and order high-volume records.",duration:"30 min",objectives:["Choose SEARCH or SEARCH ALL","Maintain sorted tables","Define sort input and output procedures"],concept:"SEARCH scans a table; SEARCH ALL uses binary search and requires an ordered table. SORT can order files using declarative keys and procedures.",code:`SEARCH ALL CUSTOMER-ENTRY\n    AT END MOVE "Y" TO NOT-FOUND-FLAG\n    WHEN CUSTOMER-ID(CUST-IDX) = LOOKUP-ID\n         MOVE CUSTOMER-NAME(CUST-IDX) TO RESULT-NAME\nEND-SEARCH.`,practice:"Build a sorted product lookup table and search by SKU.",next:"record-layouts"},
{slug:"record-layouts",track:"Data structures",number:12,title:"Records, REDEFINES & 88s",summary:"Model rich business records without wasting storage.",duration:"28 min",objectives:["Create nested groups","Overlay data with REDEFINES","Use 66 and 88 levels appropriately"],concept:"Group levels create hierarchy. REDEFINES provides another view of the same bytes, useful for variant records and raw date fields.",code:`01 RAW-DATE PIC 9(8).\n01 DATE-PARTS REDEFINES RAW-DATE.\n   05 DATE-YEAR  PIC 9(4).\n   05 DATE-MONTH PIC 99.\n   05 DATE-DAY   PIC 99.`,practice:"Model a transaction that may be a card payment or bank transfer.",next:"sequential-files"},
{slug:"sequential-files",track:"Files & records",number:13,title:"Sequential files",summary:"Read and write batch files record by record.",duration:"35 min",objectives:["Connect SELECT and FD entries","Handle end-of-file","Check FILE STATUS"],concept:"Sequential files are the workhorse of batch processing. Programs open them, process records in order, and close them on every path.",code:`OPEN INPUT CUSTOMER-FILE\nPERFORM UNTIL END-OF-FILE\n    READ CUSTOMER-FILE\n       AT END SET END-OF-FILE TO TRUE\n       NOT AT END PERFORM PROCESS-CUSTOMER\n    END-READ\nEND-PERFORM\nCLOSE CUSTOMER-FILE.`,practice:"Copy valid records to one file and rejected records to another.",next:"indexed-files"},
{slug:"indexed-files",track:"Files & records",number:14,title:"Indexed & relative files",summary:"Access records directly by business key or relative position.",duration:"38 min",objectives:["Define primary and alternate keys","Use START and dynamic access","Interpret file status codes"],concept:"Indexed files support keyed access and ordered traversal. Relative files address fixed slots by relative record number.",code:`MOVE LOOKUP-ID TO CUSTOMER-ID\nREAD CUSTOMER-FILE KEY IS CUSTOMER-ID\n    INVALID KEY MOVE "NOT FOUND" TO RESULT-MESSAGE\n    NOT INVALID KEY PERFORM DISPLAY-CUSTOMER\nEND-READ.`,practice:"Build a customer lookup supporting both ID and last-name access.",next:"file-updates"},
{slug:"file-updates",track:"Files & records",number:15,title:"WRITE, REWRITE & DELETE",summary:"Make controlled, status-aware file changes.",duration:"30 min",objectives:["Choose WRITE or REWRITE","Delete indexed records safely","Design audit output"],concept:"WRITE creates records, REWRITE replaces a record previously read, and DELETE removes by key. Always inspect file status after mutation.",code:`REWRITE CUSTOMER-RECORD\n    INVALID KEY PERFORM LOG-UPDATE-ERROR\n    NOT INVALID KEY PERFORM WRITE-AUDIT-RECORD\nEND-REWRITE.`,practice:"Update an account address and write before/after values to an audit file.",next:"subprograms"},
{slug:"subprograms",track:"Production",number:16,title:"Subprograms & CALL",summary:"Create reusable modules with explicit data contracts.",duration:"32 min",objectives:["Define LINKAGE SECTION items","Pass BY REFERENCE and BY VALUE","Return status without hidden state"],concept:"CALL transfers control to another program. The called program describes parameters in LINKAGE SECTION and lists them on PROCEDURE DIVISION USING.",code:`CALL "TAXCALC" USING\n    BY REFERENCE TAX-REQUEST\n    BY REFERENCE TAX-RESPONSE\n    BY VALUE REQUEST-LENGTH\nEND-CALL.`,practice:"Extract a validation routine into a subprogram with a return code.",next:"intrinsic-functions"},
{slug:"intrinsic-functions",track:"Production",number:17,title:"Intrinsic functions",summary:"Use portable built-ins for dates, math, statistics, and text.",duration:"28 min",objectives:["Convert dates with INTEGER-OF-DATE","Use NUMVAL safely","Apply aggregate functions"],concept:"Intrinsic functions return values without external routines. Common examples include CURRENT-DATE, LENGTH, TRIM, NUMVAL, MAX, and INTEGER-OF-DATE.",code:`MOVE FUNCTION CURRENT-DATE TO WS-TIMESTAMP.\nCOMPUTE DAYS-OPEN = FUNCTION INTEGER-OF-DATE(TODAY)\n                  - FUNCTION INTEGER-OF-DATE(OPEN-DATE).`,practice:"Calculate a customer's age on a supplied processing date.",next:"embedded-sql"},
{slug:"embedded-sql",track:"Production",number:18,title:"Embedded SQL & DB2",summary:"Issue database queries and handle SQL outcomes predictably.",duration:"42 min",objectives:["Declare host variables","Use singleton SELECT and cursors","Check SQLCODE"],concept:"Embedded SQL is precompiled into calls to the database runtime. Host variables bridge COBOL data and SQL values; indicator variables represent nulls.",code:`EXEC SQL\n   SELECT CUSTOMER_NAME, BALANCE\n     INTO :WS-NAME, :WS-BALANCE\n     FROM CUSTOMER\n    WHERE CUSTOMER_ID = :WS-ID\nEND-EXEC.\nEVALUATE SQLCODE\n   WHEN 0 CONTINUE\n   WHEN 100 MOVE "NOT FOUND" TO WS-STATUS\n   WHEN OTHER PERFORM SQL-ERROR\nEND-EVALUATE.`,practice:"Write a cursor that lists all overdue invoices by due date.",next:"jcl-batch"},
{slug:"jcl-batch",track:"Production",number:19,title:"JCL & batch operations",summary:"Run COBOL programs as reliable, restartable production jobs.",duration:"40 min",objectives:["Read JOB, EXEC, and DD statements","Pass datasets to programs","Use return codes and conditions"],concept:"JCL describes the execution environment: program, datasets, parameters, resources, and step dependencies. COBOL handles records; JCL connects them.",code:`//PAYJOB  JOB (ACCT),'PAYROLL',CLASS=A,MSGCLASS=X\n//RUNPAY  EXEC PGM=PAYROLL\n//EMPIN   DD DSN=CORP.PAYROLL.INPUT,DISP=SHR\n//PAYOUT  DD DSN=CORP.PAYROLL.OUTPUT,\n//            DISP=(NEW,CATLG,DELETE),SPACE=(CYL,(5,2))`,practice:"Add a sort step before payroll and run the program only when sort returns zero.",next:"cics"},
{slug:"cics",track:"Production",number:20,title:"CICS transactions",summary:"Understand conversational and pseudo-conversational online programs.",duration:"45 min",objectives:["Explain task and transaction boundaries","Use COMMAREA safely","Handle RESP codes"],concept:"CICS coordinates online transactions, terminals, files, and recovery. Pseudo-conversational design ends each task while preserving the small state needed for the next interaction.",code:`EXEC CICS READ\n   FILE('CUSTFILE')\n   INTO(CUSTOMER-RECORD)\n   RIDFLD(CUSTOMER-ID)\n   RESP(WS-RESP)\nEND-EXEC.`,practice:"Design a two-screen customer inquiry using a COMMAREA.",next:"testing"},
{slug:"testing",track:"Modernization",number:21,title:"Testing & debugging",summary:"Make legacy changes safer with characterization tests and diagnostics.",duration:"36 min",objectives:["Create boundary-focused test data","Use compiler diagnostics","Capture current behavior before refactoring"],concept:"Good COBOL tests emphasize data boundaries: field limits, signs, rounding, invalid codes, EOF, missing keys, and restart points.",code:`IF ACTUAL-TOTAL NOT = EXPECTED-TOTAL\n    DISPLAY "FAIL: expected=" EXPECTED-TOTAL\n            " actual=" ACTUAL-TOTAL\n    ADD 1 TO FAILURE-COUNT\nEND-IF.`,practice:"Create a test table covering zero, negative, maximum, and rounding cases.",next:"modernization"},
{slug:"modernization",track:"Modernization",number:22,title:"Modern COBOL delivery",summary:"Use Git, CI, containers, APIs, and incremental modernization.",duration:"38 min",objectives:["Compile in CI","Identify stable seams","Avoid high-risk rewrites"],concept:"Modernization works best incrementally: lock behavior with tests, isolate data contracts, automate builds, then expose or replace capabilities behind stable interfaces.",code:`# CI build with GnuCOBOL\ncobc -x -free -Wall src/payroll.cbl -o build/payroll\n./build/payroll < test/fixtures/payroll.in\ndiff test/expected/payroll.out actual.out`,practice:"Draw the input, output, database, and calling-system boundaries around one legacy program."}
];

export const lessonBySlug = (slug:string) => lessons.find(l=>l.slug===slug);
export const projects = [
{slug:"payroll",title:"Payroll processor",level:"Intermediate",domain:"Batch",description:"Overtime, deductions, taxes, formatted pay statements, and rejects."},
{slug:"banking-ledger",title:"Banking ledger",level:"Advanced",domain:"Files",description:"Post credits and debits with audit trails and balance controls."},
{slug:"invoice",title:"Invoice generator",level:"Intermediate",domain:"Reports",description:"Line items, discounts, tax, totals, and print-ready formatting."},
{slug:"inventory",title:"Inventory manager",level:"Intermediate",domain:"Indexed files",description:"Search, receive, sell, reorder, and value stock by SKU."},
{slug:"atm",title:"ATM simulator",level:"Advanced",domain:"Transactions",description:"PIN validation, withdrawals, deposits, limits, and receipts."},
{slug:"hotel",title:"Hotel booking",level:"Advanced",domain:"Data modeling",description:"Availability, reservations, pricing, and guest folios."},
{slug:"csv-importer",title:"CSV importer",level:"Beginner",domain:"Text",description:"Parse, validate, normalize, accept, and reject incoming rows."},
{slug:"report-writer",title:"Sales report writer",level:"Intermediate",domain:"Reports",description:"Control breaks, subtotals, page headings, and grand totals."},
{slug:"loan",title:"Loan amortization",level:"Intermediate",domain:"Finance",description:"Payment schedules, principal, interest, and final adjustments."},
{slug:"customer-master",title:"Customer master",level:"Advanced",domain:"CRUD",description:"Keyed inquiry, add, update, delete, validation, and audit history."}
];
