"use client";

import Link from "next/link";
import { useMemo, useState } from "react";

const systems = [
  { id:"ledger", n:"01", domain:"GLOBAL PAYMENTS", title:"Exactly-once payment ledger", desc:"CICS + DB2 transaction processing with idempotency keys, optimistic locking, outbox events, compensating reversals, and tamper-evident audit chains.", scale:"32K TPS", rto:"< 8 sec", stack:["Enterprise COBOL","CICS TS","DB2 for z/OS","IBM MQ"], color:"acid" },
  { id:"fraud", n:"02", domain:"REAL-TIME RISK", title:"Streaming fraud decision engine", desc:"Score authorizations under 12ms using shared-memory feature tables, rules compiled from decision graphs, explainable outcomes, and a Kafka bridge.", scale:"8.4B/day", rto:"11 ms p99", stack:["COBOL","CICS","VSAM RLS","Kafka"], color:"cyan" },
  { id:"digital-twin", n:"03", domain:"MODERNIZATION", title:"Behavioral digital twin", desc:"Capture production inputs and outputs, replay them against a strangler service, and prove semantic equivalence at field and business-rule level.", scale:"10M cases", rto:"99.9997% match", stack:["GnuCOBOL","z/OS","OpenTelemetry","Kubernetes"], color:"coral" },
  { id:"temporal", n:"04", domain:"CORE BANKING", title:"Bi-temporal account engine", desc:"Reconstruct what the bank knew at any past instant using effective-time and system-time records, retroactive corrections, and deterministic replay.", scale:"70 years", rto:"μs lookup", stack:["COBOL","DB2 Temporal","CICS","zIIP"], color:"amber" },
  { id:"quantum", n:"05", domain:"CRYPTO AGILITY", title:"Post-quantum key migration", desc:"Inventory cryptographic dependencies, dual-sign high-value messages, rotate key material without downtime, and preserve audit verification across epochs.", scale:"4.2B keys", rto:"Zero downtime", stack:["COBOL","ICSF","RACF","PKCS #11"], color:"violet" },
  { id:"ai", n:"06", domain:"SAFE AI", title:"Explainable anomaly copilot", desc:"Feed redacted operational signals to an AI sidecar while COBOL retains deterministic authority, policy gates, provenance, and human override.", scale:"1.8M signals/s", rto:"100% governed", stack:["COBOL","z/OS Connect","watsonx","OPA"], color:"blue" },
];

const code:Record<string,string> = {
  ledger:`EXEC CICS SYNCPOINT END-EXEC\n\nEXEC SQL\n  INSERT INTO PAYMENT_COMMAND\n    (IDEMPOTENCY_KEY, ACCOUNT_ID, AMOUNT, STATUS)\n  VALUES\n    (:WS-IDEMPOTENCY-KEY, :WS-ACCOUNT-ID,\n     :WS-AMOUNT, 'RECEIVED')\nEND-EXEC\n\nEVALUATE SQLCODE\n  WHEN 0\n    PERFORM POST-DOUBLE-ENTRY-LEDGER\n    PERFORM APPEND-OUTBOX-EVENT\n  WHEN -803\n    PERFORM RETURN-PRIOR-RESULT\n  WHEN OTHER\n    PERFORM MAP-DB2-FAILURE\nEND-EVALUATE\n\nIF COMMAND-COMMITTED\n  EXEC CICS SYNCPOINT END-EXEC\nELSE\n  EXEC CICS SYNCPOINT ROLLBACK END-EXEC\nEND-IF`,
  fraud:`COMPUTE WS-RISK-SCORE =\n    (VELOCITY-WEIGHT * TXN-COUNT-5M) +\n    (DISTANCE-WEIGHT * GEO-DISTANCE) +\n    (NOVELTY-WEIGHT  * MERCHANT-NOVELTY)\n\nEVALUATE TRUE ALSO ACCOUNT-TIER\n  WHEN WS-RISK-SCORE >= HARD-BLOCK ALSO ANY\n    SET DECISION-DENY TO TRUE\n    MOVE "R901" TO REASON-CODE\n  WHEN WS-RISK-SCORE >= CHALLENGE ALSO "P"\n    SET DECISION-STEP-UP TO TRUE\n    MOVE "R410" TO REASON-CODE\n  WHEN OTHER\n    SET DECISION-APPROVE TO TRUE\nEND-EVALUATE\n\nCALL "EMITDECISION" USING\n  BY REFERENCE DECISION-ENVELOPE\n  BY VALUE LENGTH OF DECISION-ENVELOPE`,
  "digital-twin":`CALL "NORMALIZE" USING PROD-RESULT CANONICAL-PROD\nCALL "NORMALIZE" USING TWIN-RESULT CANONICAL-TWIN\n\nIF CANONICAL-PROD = CANONICAL-TWIN\n   ADD 1 TO EXACT-MATCH-COUNT\nELSE\n   PERFORM VARYING FIELD-IDX FROM 1 BY 1\n      UNTIL FIELD-IDX > CONTRACT-FIELD-COUNT\n      IF PROD-FIELD(FIELD-IDX) NOT = TWIN-FIELD(FIELD-IDX)\n         PERFORM CAPTURE-SEMANTIC-DIFF\n      END-IF\n   END-PERFORM\nEND-IF\n\nCOMPUTE EQUIVALENCE-RATE =\n  EXACT-MATCH-COUNT / TOTAL-REPLAY-COUNT * 100`,
  temporal:`EXEC SQL\n SELECT BALANCE, STATUS, CREDIT_LIMIT\n   INTO :WS-BALANCE, :WS-STATUS, :WS-LIMIT\n   FROM ACCOUNT\n   FOR SYSTEM_TIME AS OF :WS-KNOWLEDGE-TIME\n  WHERE ACCOUNT_ID = :WS-ACCOUNT-ID\n    AND :WS-EFFECTIVE-TIME BETWEEN\n        VALID_FROM AND VALID_TO\nEND-EXEC`,
  quantum:`EVALUATE SIGNATURE-EPOCH\n WHEN LEGACY-EPOCH\n   CALL "ICSF-VERIFY-RSA" USING SIGNATURE-CONTEXT\n WHEN HYBRID-EPOCH\n   CALL "ICSF-VERIFY-RSA" USING SIGNATURE-CONTEXT\n   CALL "PQC-VERIFY-MLDSA" USING SIGNATURE-CONTEXT\n   IF RSA-VALID AND MLDSA-VALID\n      SET SIGNATURE-VALID TO TRUE\n   END-IF\n WHEN PQC-EPOCH\n   CALL "PQC-VERIFY-MLDSA" USING SIGNATURE-CONTEXT\n WHEN OTHER\n   SET UNSUPPORTED-EPOCH TO TRUE\nEND-EVALUATE`,
  ai:`MOVE ZERO TO DISCLOSURE-COUNT\nPERFORM VARYING FIELD-IDX FROM 1 BY 1\n  UNTIL FIELD-IDX > SIGNAL-FIELD-COUNT\n  EVALUATE CLASSIFICATION(FIELD-IDX)\n    WHEN "PUBLIC" PERFORM COPY-SIGNAL-FIELD\n    WHEN "TOKEN"  PERFORM TOKENIZE-SIGNAL-FIELD\n    WHEN "SECRET" PERFORM REDACT-SIGNAL-FIELD\n  END-EVALUATE\nEND-PERFORM\n\nCALL "POLICYGATE" USING AI-REQUEST POLICY-DECISION\nIF POLICY-ALLOWS AND HUMAN-OVERRIDE NOT ACTIVE\n   CALL "AISIDECAR" USING AI-REQUEST AI-ADVISORY\nEND-IF\nPERFORM DETERMINISTIC-FINAL-DECISION`
};

function Topology(){const [failed,setFailed]=useState<string[]>([]);const nodes=["API gateway","CICS region A","CICS region B","DB2 data sharing","Outbox relay","Event mesh"];const toggle=(n:string)=>setFailed(f=>f.includes(n)?f.filter(x=>x!==n):[...f,n]);return <div className="frontier-tool"><div className="lab-head"><div><small>INTERACTIVE / FAILURE LAB</small><h3>Resiliency topology</h3></div><span className={failed.length>1?"danger":"healthy"}>{failed.length>1?"DEGRADED":"FAULT TOLERANT"}</span></div><p>Take components offline. The model traces whether authorization and settlement remain available.</p><div className="topology">{nodes.map((n,i)=><button key={n} onClick={()=>toggle(n)} className={failed.includes(n)?"failed":""}><i>{String(i+1).padStart(2,"0")}</i><b>{n}</b><span>{failed.includes(n)?"OFFLINE":"ACTIVE"}</span></button>)}</div><div className="lab-result"><b>{failed.length===0?"All paths nominal":failed.length===1?"Traffic rerouted; no transaction loss":"Settlement paused; commands retained for replay"}</b><span>{failed.length===0?"2 active regions · synchronous commit":failed.length===1?"Recovery objective maintained":"Idempotent backlog protected"}</span></div></div>}

function Capacity(){const [tps,setTps]=useState(12000);const [bytes,setBytes]=useState(640);const result=useMemo(()=>({day:(tps*86400).toLocaleString(),gb:((tps*bytes*86400)/1e9).toFixed(1),partitions:Math.ceil(tps/2500)}),[tps,bytes]);return <div className="frontier-tool capacity"><div className="lab-head"><div><small>INTERACTIVE / CAPACITY LAB</small><h3>Transaction envelope</h3></div><span className="healthy">LIVE MODEL</span></div><label>Peak transactions / second <b>{tps.toLocaleString()}</b><input type="range" min="1000" max="50000" step="1000" value={tps} onChange={e=>setTps(+e.target.value)}/></label><label>Event payload bytes <b>{bytes}</b><input type="range" min="128" max="4096" step="128" value={bytes} onChange={e=>setBytes(+e.target.value)}/></label><div className="capacity-results"><span><b>{result.day}</b>transactions/day</span><span><b>{result.gb} GB</b>event stream/day</span><span><b>{result.partitions}</b>minimum partitions</span></div></div>}

export default function Frontier(){const [active,setActive]=useState("ledger");const current=systems.find(s=>s.id===active)!;return <div className="frontier-page"><header className="frontier-nav"><Link href="/" className="brand"><span className="brand-mark">C</span><span>COBOL.campus</span></Link><span className="frontier-badge">FRONTIER LAB / R&D</span><nav><a href="#systems">Systems</a><a href="#lab">Failure lab</a><a href="#patterns">Patterns</a></nav><Link href="/course">Core curriculum →</Link></header><main><section className="frontier-hero"><div className="frontier-grid"/><div className="orbit orbit-a"/><div className="orbit orbit-b"/><div className="hero-index">ADVANCED SYSTEMS ENGINEERING<br/>COBOL / Z / DISTRIBUTED SYSTEMS</div><h1>Past best practice.<br/><em>Into the frontier.</em></h1><p>Architectures for systems that cannot lose a cent, repeat a command, expose a secret, or stop operating—built on COBOL&apos;s deterministic core and the edge of modern infrastructure.</p><div className="frontier-stats"><span><b>10⁹+</b> events / day</span><span><b>99.999%</b> availability</span><span><b>&lt;12ms</b> decisions</span><span><b>0</b> tolerance for drift</span></div><a href="#systems" className="frontier-cta">Enter the systems lab <b>↓</b></a></section>
<section className="frontier-systems" id="systems"><div className="frontier-section-title"><span>01 / REFERENCE ARCHITECTURES</span><h2>Six systems at<br/>the edge of possible.</h2><p>Each blueprint combines deterministic business logic with distributed-systems guarantees, operational controls, and evolutionary seams.</p></div><div className="system-selector">{systems.map(s=><button key={s.id} onClick={()=>setActive(s.id)} className={active===s.id?"active":""}><span>{s.n}</span><b>{s.title}</b><small>{s.domain}</small></button>)}</div><article className={`system-detail ${current.color}`}><div className="system-copy"><span>{current.domain} / BLUEPRINT {current.n}</span><h3>{current.title}</h3><p>{current.desc}</p><div className="system-metrics"><span><b>{current.scale}</b>throughput / scale</span><span><b>{current.rto}</b>operating target</span></div><div className="stack">{current.stack.map(x=><i key={x}>{x}</i>)}</div></div><div className="frontier-code"><div><span>core-transaction.cbl</span><b>PRODUCTION PATTERN</b></div><pre><code>{code[active]}</code></pre><footer><span>EXPLICIT SCOPE</span><span>STATUS-AWARE</span><span>REPLAY-SAFE</span></footer></div></article></section>
<section className="frontier-lab" id="lab"><div className="frontier-section-title light"><span>02 / ENGINEERING WORKBENCH</span><h2>Break it here.<br/>Not in production.</h2><p>Explore failure domains and capacity constraints before they become incidents.</p></div><div className="lab-grid"><Topology/><Capacity/></div></section>
<section className="pattern-section" id="patterns"><div className="frontier-section-title"><span>03 / FRONTIER PATTERN LIBRARY</span><h2>The patterns behind<br/>unbreakable systems.</h2></div><div className="pattern-grid">{[["01","Idempotent command","Every external command carries a durable identity. Replays return the original outcome instead of repeating work."],["02","Transactional outbox","State change and event intent commit together. Publication may retry forever without dual-write drift."],["03","Hash-chained audit","Each audit record seals the previous digest, making retroactive alteration detectable across storage tiers."],["04","Deterministic replay","Given the same canonical inputs and rule version, the system must produce byte-equivalent business outcomes."],["05","Bi-temporal truth","Effective time answers what was true; system time answers what the institution knew and when it knew it."],["06","Strangler seam","A stable contract routes one capability at a time, allowing rollback without splitting a transaction boundary."],["07","Bulkhead region","Independent workloads have separate pools, queues, limits, and recovery so one failure cannot consume the system."],["08","Crypto epoch","Every signed artifact carries an algorithm era, supporting verification through decades of key migration."]].map(p=><article key={p[0]}><span>{p[0]}</span><h3>{p[1]}</h3><p>{p[2]}</p><b>VIEW IMPLEMENTATION ↗</b></article>)}</div></section>
<section className="frontier-manifesto"><small>THE FRONTIER PRINCIPLE</small><blockquote>“Modern” is not a language.<br/>It is a system that can <em>prove</em><br/>what it did, survive repetition,<br/>and evolve without losing truth.</blockquote><Link href="/projects">Build from the project library <span>→</span></Link></section></main></div>}
