import Link from "next/link";
import { notFound } from "next/navigation";

const projects: Record<string, { title: string; type: string; intro: string; code: string }> = {
  payroll: { title: "Payroll processor", type: "BATCH APPLICATION", intro: "A complete miniature payroll run: accept hours and rate, calculate regular and overtime pay, deduct tax, and print an aligned pay statement.", code: `       IDENTIFICATION DIVISION.\n       PROGRAM-ID. PAYROLL.\n       DATA DIVISION.\n       WORKING-STORAGE SECTION.\n       01 WS-HOURS       PIC 9(3)V99 VALUE 42.\n       01 WS-RATE        PIC 9(3)V99 VALUE 25.\n       01 WS-GROSS       PIC 9(6)V99.\n       01 WS-TAX         PIC 9(6)V99.\n       01 WS-NET         PIC 9(6)V99.\n       PROCEDURE DIVISION.\n           IF WS-HOURS > 40\n              COMPUTE WS-GROSS = (40 * WS-RATE) +\n                 ((WS-HOURS - 40) * WS-RATE * 1.5)\n           ELSE\n              COMPUTE WS-GROSS = WS-HOURS * WS-RATE\n           END-IF\n           COMPUTE WS-TAX = WS-GROSS * 0.22\n           COMPUTE WS-NET = WS-GROSS - WS-TAX\n           DISPLAY "GROSS: " WS-GROSS\n           DISPLAY "NET:   " WS-NET\n           STOP RUN.` },
  "banking-ledger": { title: "Banking ledger", type: "FILE PROCESSING", intro: "Process debit and credit transactions while preserving an auditable running balance and rejecting overdrafts.", code: `       EVALUATE TXN-TYPE\n          WHEN "C" ADD TXN-AMOUNT TO ACCOUNT-BALANCE\n          WHEN "D"\n             IF TXN-AMOUNT <= ACCOUNT-BALANCE\n                SUBTRACT TXN-AMOUNT FROM ACCOUNT-BALANCE\n             ELSE\n                MOVE "NSF" TO TXN-STATUS\n             END-IF\n          WHEN OTHER MOVE "ERR" TO TXN-STATUS\n       END-EVALUATE.` },
  invoice: { title: "Invoice generator", type: "REPORTING", intro: "Format a business invoice from line items with quantities, prices, tax, totals, and print-safe numeric editing.", code: `       01 PRINT-LINE.\n          05 P-DESCRIPTION PIC X(24).\n          05 P-QUANTITY    PIC ZZ9.\n          05 P-PRICE       PIC $$$,$$9.99.\n          05 P-TOTAL       PIC $$$,$$9.99.\n\n       COMPUTE LINE-TOTAL = ITEM-QUANTITY * ITEM-PRICE\n       MOVE LINE-TOTAL TO P-TOTAL\n       WRITE PRINT-LINE AFTER ADVANCING 1 LINE.` },
};

export default async function ProjectPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const project = projects[slug]; if (!project) notFound(); return <div className="lesson-shell"><aside className="lesson-side"><Link href="/" className="brand"><span className="brand-mark">C</span><span>COBOL.campus</span></Link><small>SAMPLE APPLICATIONS</small><nav><Link href="/projects/payroll">Payroll processor</Link><Link href="/projects/banking-ledger">Banking ledger</Link><Link href="/projects/invoice">Invoice generator</Link><Link href="/#projects">← All projects</Link></nav></aside><main className="lesson-main"><Link className="back-mobile" href="/#projects">← PROJECTS</Link><div className="breadcrumb">PROJECT / {project.type}</div><h1>{project.title}</h1><p className="lead">{project.intro}</p><div className="lesson-meta"><span>COMPLETE SOURCE</span><span>ANNOTATED</span><span>GNUCOBOL</span></div><article className="article"><h2>The program</h2><p>Read the source once for flow, then trace each data item as it changes. Production versions would add file-status checks, validation, structured error handling, and automated tests.</p><pre className="code-block project-code"><code>{project.code}</code></pre><div className="callout"><b>TRY THIS</b><br />Change one business rule, predict the output on paper, then compile and compare. That feedback loop builds fluency quickly.</div><h2>Production extensions</h2><ul><li>Read input from a validated sequential or indexed file.</li><li>Return meaningful status codes to the calling job.</li><li>Write rejects to a separate audit dataset.</li><li>Add tests for zeros, limits, signs, and invalid codes.</li></ul></article><div className="lesson-next"><span>Build the next system.</span><Link href="/projects/banking-ledger">Next project →</Link></div></main></div>; }
