import Link from "next/link";
import { notFound } from "next/navigation";

const lessons: Record<string, { title: string; eyebrow: string; lead: string; duration: string; body: React.ReactNode }> = {
  "getting-started": { title: "Meet COBOL.", eyebrow: "FOUNDATIONS / LESSON 01", lead: "Write, compile, and understand your first COBOL program—then learn why its unusually explicit structure is a feature, not a flaw.", duration: "12 MIN", body: <><h2>What is COBOL?</h2><p>COBOL is a compiled language designed around readable business logic and exact decimal arithmetic. Its name stands for Common Business-Oriented Language. Decades later, it remains central to banking, insurance, government, and large-scale transaction processing.</p><div className="callout"><b>MENTAL MODEL</b><br />A COBOL program is a carefully labeled filing cabinet. Divisions are drawers, sections are folders, paragraphs are documents, and statements do the work.</div><h2>Your first program</h2><p>Save this as <code>hello.cbl</code>. The leading spaces reflect traditional fixed-format source layout; modern compilers can also accept free format.</p><pre className="code-block"><code>{`       IDENTIFICATION DIVISION.\n       PROGRAM-ID. HELLO-COBOL.\n       PROCEDURE DIVISION.\n           DISPLAY "Hello, mainframe."\n           STOP RUN.`}</code></pre><h2>Read it top to bottom</h2><ul><li><b>IDENTIFICATION DIVISION</b> names and documents the program.</li><li><b>PROGRAM-ID</b> supplies the program name to the compiler.</li><li><b>PROCEDURE DIVISION</b> contains executable statements.</li><li><b>DISPLAY</b> writes text; <b>STOP RUN</b> returns control to the operating system.</li></ul><h2>Compile with GnuCOBOL</h2><pre className="code-block"><code>{`cobc -x -free hello.cbl\n./hello\n# Hello, mainframe.`}</code></pre></> },
  "business-logic": { title: "Business logic.", eyebrow: "TRACK 02 / OVERVIEW", lead: "Turn requirements into precise arithmetic, branching, and repeatable procedures.", duration: "18 LESSONS", body: <><h2>The verbs of business</h2><p>COBOL reads like a controlled form of English. MOVE changes data, COMPUTE evaluates formulas, IF and EVALUATE choose paths, and PERFORM structures repetition.</p><pre className="code-block"><code>{`COMPUTE WS-NET-PAY = WS-GROSS-PAY - WS-TAX.\nIF WS-NET-PAY > 0\n    DISPLAY "PAYMENT APPROVED"\nELSE\n    DISPLAY "REVIEW REQUIRED"\nEND-IF.`}</code></pre></> },
  "files-&-records": { title: "Files & records.", eyebrow: "TRACK 03 / OVERVIEW", lead: "Model fixed business records and process them safely at scale.", duration: "15 LESSONS", body: <><h2>Records are the center</h2><p>COBOL&apos;s data hierarchy maps naturally to business documents. Group items contain elementary fields, each described by a PICTURE clause.</p><pre className="code-block"><code>{`01 CUSTOMER-RECORD.\n   05 CUSTOMER-ID      PIC 9(8).\n   05 CUSTOMER-NAME    PIC X(30).\n   05 ACCOUNT-BALANCE  PIC S9(7)V99 COMP-3.`}</code></pre></> },
  "production-cobol": { title: "Production COBOL.", eyebrow: "TRACK 04 / OVERVIEW", lead: "Connect COBOL to the mainframe ecosystem: JCL, DB2, CICS, testing, observability, and modernization.", duration: "22 LESSONS", body: <><h2>Beyond the language</h2><p>Production work combines language skill with platform knowledge. Batch programs run under JCL, online transactions commonly use CICS, and data may live in DB2 or VSAM.</p><div className="callout"><b>THE PRODUCTION RULE</b><br />Treat data contracts, return codes, restartability, and audit trails as first-class features.</div></> },
};

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; return { title: lessons[slug]?.title ?? "Lesson" }; }
export default async function Lesson({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const lesson = lessons[slug]; if (!lesson) notFound(); return <div className="lesson-shell"><aside className="lesson-side"><Link href="/" className="brand"><span className="brand-mark">C</span><span>COBOL.campus</span></Link><small>FOUNDATIONS</small><nav><Link className={slug === "getting-started" ? "active" : ""} href="/learn/getting-started">01 — Meet COBOL</Link><a href="#structure">02 — Program structure</a><a href="#data">03 — Data & PIC</a><a href="#move">04 — The MOVE verb</a><Link href="/">← Course home</Link></nav></aside><main className="lesson-main"><Link className="back-mobile" href="/">← COURSE HOME</Link><div className="breadcrumb">{lesson.eyebrow}</div><h1>{lesson.title}</h1><p className="lead">{lesson.lead}</p><div className="lesson-meta"><span>{lesson.duration}</span><span>BEGINNER FRIENDLY</span><span>WITH CODE</span></div><article className="article">{lesson.body}</article><div className="lesson-next"><span>Lesson complete? Keep the momentum.</span><Link href="/learn/business-logic">Next lesson →</Link></div></main></div>; }
