export const airlineFiles = [
{path:"copybooks/AIRCOM.cpy",type:"COPYBOOK",description:"Shared request, response, passenger, itinerary, and status contracts.",code:`       01  AIR-REQUEST.
           05 AIR-REQUEST-ID          PIC X(26).
           05 AIR-OPERATION           PIC X(8).
              88 AIR-OP-SEARCH        VALUE "SEARCH".
              88 AIR-OP-BOOK          VALUE "BOOK".
              88 AIR-OP-CANCEL        VALUE "CANCEL".
              88 AIR-OP-CHECKIN       VALUE "CHECKIN".
           05 AIR-CHANNEL             PIC X(3).
           05 AIR-IDEMPOTENCY-KEY     PIC X(36).
           05 AIR-FLIGHT-KEY.
              10 AIR-CARRIER          PIC X(3).
              10 AIR-FLIGHT-NUMBER    PIC 9(4).
              10 AIR-DEPARTURE-DATE   PIC 9(8).
           05 AIR-ORIGIN              PIC X(3).
           05 AIR-DESTINATION         PIC X(3).
           05 AIR-CABIN               PIC X.
           05 AIR-PARTY-SIZE          PIC 99.
           05 AIR-PASSENGERS OCCURS 9 TIMES.
              10 AIR-PASSENGER-ID     PIC X(20).
              10 AIR-FIRST-NAME       PIC X(30).
              10 AIR-LAST-NAME        PIC X(30).
              10 AIR-LOYALTY-NUMBER   PIC X(16).
       01  AIR-RESPONSE.
           05 AIR-RESPONSE-CODE       PIC X(4).
           05 AIR-RESPONSE-MESSAGE    PIC X(80).
           05 AIR-PNR                 PIC X(6).
           05 AIR-TICKET-TOTAL        PIC S9(7)V99 COMP-3.
           05 AIR-CONFIRMED-COUNT     PIC 99.
           05 AIR-WAITLIST-COUNT      PIC 99.
           05 AIR-RETURN-CODE         PIC S9(4) COMP.
           05 AIR-TRACE-ID            PIC X(32).`},
{path:"copybooks/AIRSQL.cpy",type:"COPYBOOK",description:"DB2 communication and standardized database diagnostics.",code:`       01  AIR-SQL-CONTEXT.
           05 AIR-SQLCODE             PIC S9(9) COMP.
           05 AIR-SQLSTATE            PIC X(5).
           05 AIR-SQL-OPERATION       PIC X(20).
           05 AIR-SQL-TABLE           PIC X(18).
           05 AIR-SQL-ROWS            PIC S9(9) COMP.
           05 AIR-SQL-MESSAGE         PIC X(120).
       01  AIR-FILE-STATUS            PIC XX.
           88 AIR-FILE-OK             VALUE "00".
           88 AIR-FILE-EOF            VALUE "10".
       01  AIR-RETRY-CONTROL.
           05 AIR-RETRY-COUNT         PIC 9 VALUE ZERO.
           05 AIR-MAX-RETRIES         PIC 9 VALUE 3.
           05 AIR-RETRYABLE           PIC X VALUE "N".
              88 AIR-CAN-RETRY        VALUE "Y".`},
{path:"src/AIRROUTE.cbl",type:"ONLINE",description:"CICS transaction router, validation boundary, idempotency guard, and unit-of-work owner.",code:`       IDENTIFICATION DIVISION.
       PROGRAM-ID. AIRROUTE.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-COMMAREA-LENGTH          PIC S9(4) COMP VALUE ZERO.
       01 WS-PROGRAM                  PIC X(8).
       01 WS-UOW-COMMITTED            PIC X VALUE "N".
          88 UOW-COMMITTED            VALUE "Y".
       COPY AIRCOM.
       COPY AIRSQL.
       LINKAGE SECTION.
       01 DFHCOMMAREA                  PIC X(4096).
       PROCEDURE DIVISION.
       MAIN-PROCEDURE.
           PERFORM INITIALIZE-REQUEST
           PERFORM VALIDATE-ENVELOPE
           IF AIR-RETURN-CODE = ZERO
              PERFORM CHECK-IDEMPOTENCY
           END-IF
           IF AIR-RETURN-CODE = ZERO
              EVALUATE TRUE
                 WHEN AIR-OP-SEARCH  MOVE "AIRSRCH" TO WS-PROGRAM
                 WHEN AIR-OP-BOOK    MOVE "AIRBOOK" TO WS-PROGRAM
                 WHEN AIR-OP-CANCEL  MOVE "AIRCANCL" TO WS-PROGRAM
                 WHEN AIR-OP-CHECKIN MOVE "AIRCHKIN" TO WS-PROGRAM
                 WHEN OTHER
                    MOVE "E001" TO AIR-RESPONSE-CODE
                    MOVE "UNSUPPORTED OPERATION" TO AIR-RESPONSE-MESSAGE
                    MOVE 8 TO AIR-RETURN-CODE
              END-EVALUATE
           END-IF
           IF AIR-RETURN-CODE = ZERO
              EXEC CICS LINK PROGRAM(WS-PROGRAM)
                 COMMAREA(AIR-REQUEST) LENGTH(LENGTH OF AIR-REQUEST)
                 RESP(AIR-RETURN-CODE)
              END-EXEC
           END-IF
           PERFORM COMPLETE-UNIT-OF-WORK
           PERFORM SEND-RESPONSE
           EXEC CICS RETURN END-EXEC.
       INITIALIZE-REQUEST.
           INITIALIZE AIR-RESPONSE AIR-SQL-CONTEXT
           MOVE EIBCALEN TO WS-COMMAREA-LENGTH
           IF WS-COMMAREA-LENGTH > ZERO
              MOVE DFHCOMMAREA TO AIR-REQUEST
           ELSE
              MOVE "E000" TO AIR-RESPONSE-CODE
              MOVE "REQUEST BODY REQUIRED" TO AIR-RESPONSE-MESSAGE
              MOVE 8 TO AIR-RETURN-CODE
           END-IF.
       VALIDATE-ENVELOPE.
           IF AIR-REQUEST-ID = SPACES OR AIR-IDEMPOTENCY-KEY = SPACES
              MOVE "E002" TO AIR-RESPONSE-CODE
              MOVE "REQUEST AND IDEMPOTENCY IDS REQUIRED" TO AIR-RESPONSE-MESSAGE
              MOVE 8 TO AIR-RETURN-CODE
           END-IF
           IF AIR-PARTY-SIZE < 1 OR > 9
              MOVE "E003" TO AIR-RESPONSE-CODE
              MOVE "PARTY SIZE MUST BE 1 THROUGH 9" TO AIR-RESPONSE-MESSAGE
              MOVE 8 TO AIR-RETURN-CODE
           END-IF.
       CHECK-IDEMPOTENCY.
           EXEC SQL SELECT RESPONSE_CODE, PNR
             INTO :AIR-RESPONSE-CODE, :AIR-PNR
             FROM AIR_COMMAND
            WHERE IDEMPOTENCY_KEY = :AIR-IDEMPOTENCY-KEY
           END-EXEC
           IF SQLCODE = ZERO
              MOVE "PRIOR RESULT RETURNED" TO AIR-RESPONSE-MESSAGE
              MOVE 4 TO AIR-RETURN-CODE
           ELSE IF SQLCODE NOT = 100
              MOVE 12 TO AIR-RETURN-CODE
           END-IF.
       COMPLETE-UNIT-OF-WORK.
           IF AIR-RETURN-CODE < 8
              EXEC CICS SYNCPOINT END-EXEC
              SET UOW-COMMITTED TO TRUE
           ELSE
              EXEC CICS SYNCPOINT ROLLBACK END-EXEC
           END-IF.
       SEND-RESPONSE.
           EXEC CICS SEND FROM(AIR-RESPONSE)
              LENGTH(LENGTH OF AIR-RESPONSE) RESP(AIR-RETURN-CODE)
           END-EXEC.`},
{path:"src/AIRSRCH.cbl",type:"ONLINE",description:"Availability search using a DB2 cursor, married-segment availability, and bounded results.",code:`       IDENTIFICATION DIVISION.
       PROGRAM-ID. AIRSRCH.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       EXEC SQL INCLUDE SQLCA END-EXEC.
       COPY AIRCOM.
       01 WS-RESULT-COUNT             PIC 99 VALUE ZERO.
       01 WS-END-CURSOR               PIC X VALUE "N".
          88 END-CURSOR               VALUE "Y".
       01 WS-DEPARTURE-TS             PIC X(26).
       01 WS-ARRIVAL-TS               PIC X(26).
       01 WS-SEATS-AVAILABLE          PIC S9(4) COMP.
       EXEC SQL DECLARE FLIGHT-CURSOR CURSOR FOR
          SELECT F.CARRIER, F.FLIGHT_NUMBER, F.DEPARTURE_DATE,
                 F.DEPARTURE_TS, F.ARRIVAL_TS,
                 I.SEATS_TOTAL - I.SEATS_SOLD - I.SEATS_HELD
            FROM AIR_FLIGHT F JOIN AIR_INVENTORY I
              ON I.FLIGHT_ID = F.FLIGHT_ID
           WHERE F.ORIGIN = :AIR-ORIGIN
             AND F.DESTINATION = :AIR-DESTINATION
             AND F.DEPARTURE_DATE = :AIR-DEPARTURE-DATE
             AND I.CABIN = :AIR-CABIN
           ORDER BY F.DEPARTURE_TS
           FETCH FIRST 20 ROWS ONLY
       END-EXEC.
       PROCEDURE DIVISION.
       MAIN-PROCEDURE.
           EXEC SQL OPEN FLIGHT-CURSOR END-EXEC
           IF SQLCODE NOT = ZERO PERFORM DB-ERROR GOBACK END-IF
           PERFORM UNTIL END-CURSOR
              EXEC SQL FETCH FLIGHT-CURSOR
                INTO :AIR-CARRIER, :AIR-FLIGHT-NUMBER,
                     :AIR-DEPARTURE-DATE, :WS-DEPARTURE-TS,
                     :WS-ARRIVAL-TS, :WS-SEATS-AVAILABLE
              END-EXEC
              EVALUATE SQLCODE
                 WHEN 0 ADD 1 TO WS-RESULT-COUNT
                 WHEN 100 SET END-CURSOR TO TRUE
                 WHEN OTHER PERFORM DB-ERROR SET END-CURSOR TO TRUE
              END-EVALUATE
           END-PERFORM
           EXEC SQL CLOSE FLIGHT-CURSOR END-EXEC
           MOVE "0000" TO AIR-RESPONSE-CODE
           MOVE WS-RESULT-COUNT TO AIR-CONFIRMED-COUNT
           GOBACK.
       DB-ERROR.
           MOVE "D500" TO AIR-RESPONSE-CODE
           MOVE "AVAILABILITY DATABASE ERROR" TO AIR-RESPONSE-MESSAGE
           MOVE 12 TO AIR-RETURN-CODE.`},
{path:"src/AIRBOOK.cbl",type:"ONLINE",description:"Atomic reservation workflow with inventory locking, pricing, PNR creation, ticketing, and outbox event.",code:`       IDENTIFICATION DIVISION.
       PROGRAM-ID. AIRBOOK.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       EXEC SQL INCLUDE SQLCA END-EXEC.
       COPY AIRCOM.
       01 WS-FLIGHT-ID                PIC S9(18) COMP-3.
       01 WS-SEATS-AVAILABLE          PIC S9(4) COMP.
       01 WS-BASE-FARE                PIC S9(7)V99 COMP-3.
       01 WS-TAX-TOTAL                PIC S9(7)V99 COMP-3.
       01 WS-PASSENGER-IDX            PIC 99 COMP.
       PROCEDURE DIVISION.
       MAIN-PROCEDURE.
           PERFORM LOCK-INVENTORY
           IF AIR-RETURN-CODE NOT = ZERO GOBACK END-IF
           PERFORM PRICE-ITINERARY
           PERFORM CREATE-PNR
           PERFORM CREATE-PASSENGERS
           PERFORM DECREMENT-INVENTORY
           PERFORM ISSUE-TICKETS
           PERFORM WRITE-OUTBOX-EVENT
           MOVE "0000" TO AIR-RESPONSE-CODE
           MOVE "RESERVATION CONFIRMED" TO AIR-RESPONSE-MESSAGE
           MOVE AIR-PARTY-SIZE TO AIR-CONFIRMED-COUNT
           GOBACK.
       LOCK-INVENTORY.
           EXEC SQL
             SELECT I.FLIGHT_ID,
                    I.SEATS_TOTAL - I.SEATS_SOLD - I.SEATS_HELD,
                    I.BASE_FARE
               INTO :WS-FLIGHT-ID, :WS-SEATS-AVAILABLE, :WS-BASE-FARE
               FROM AIR_INVENTORY I JOIN AIR_FLIGHT F
                 ON F.FLIGHT_ID = I.FLIGHT_ID
              WHERE F.CARRIER = :AIR-CARRIER
                AND F.FLIGHT_NUMBER = :AIR-FLIGHT-NUMBER
                AND F.DEPARTURE_DATE = :AIR-DEPARTURE-DATE
                AND I.CABIN = :AIR-CABIN
              FOR UPDATE OF I.SEATS_SOLD
           END-EXEC
           EVALUATE SQLCODE
              WHEN 0
                 IF WS-SEATS-AVAILABLE < AIR-PARTY-SIZE
                    MOVE "A101" TO AIR-RESPONSE-CODE
                    MOVE "INSUFFICIENT SEATS" TO AIR-RESPONSE-MESSAGE
                    MOVE 8 TO AIR-RETURN-CODE
                 END-IF
              WHEN 100
                 MOVE "A404" TO AIR-RESPONSE-CODE
                 MOVE "FLIGHT NOT FOUND" TO AIR-RESPONSE-MESSAGE
                 MOVE 8 TO AIR-RETURN-CODE
              WHEN OTHER MOVE 12 TO AIR-RETURN-CODE
           END-EVALUATE.
       PRICE-ITINERARY.
           COMPUTE WS-TAX-TOTAL ROUNDED =
              (WS-BASE-FARE * AIR-PARTY-SIZE) * 0.075
           COMPUTE AIR-TICKET-TOTAL =
              (WS-BASE-FARE * AIR-PARTY-SIZE) + WS-TAX-TOTAL.
       CREATE-PNR.
           CALL "AIRPNR" USING AIR-REQUEST-ID AIR-PNR
           EXEC SQL INSERT INTO AIR_RESERVATION
             (PNR, FLIGHT_ID, CABIN, PARTY_SIZE, TOTAL_AMOUNT, STATUS)
             VALUES (:AIR-PNR, :WS-FLIGHT-ID, :AIR-CABIN,
                     :AIR-PARTY-SIZE, :AIR-TICKET-TOTAL, 'HK')
           END-EXEC.
       CREATE-PASSENGERS.
           PERFORM VARYING WS-PASSENGER-IDX FROM 1 BY 1
              UNTIL WS-PASSENGER-IDX > AIR-PARTY-SIZE
              EXEC SQL INSERT INTO AIR_PASSENGER
                (PNR, PASSENGER_SEQ, FIRST_NAME, LAST_NAME, LOYALTY_NUMBER)
                VALUES (:AIR-PNR, :WS-PASSENGER-IDX,
                  :AIR-FIRST-NAME(WS-PASSENGER-IDX),
                  :AIR-LAST-NAME(WS-PASSENGER-IDX),
                  :AIR-LOYALTY-NUMBER(WS-PASSENGER-IDX))
              END-EXEC
           END-PERFORM.
       DECREMENT-INVENTORY.
           EXEC SQL UPDATE AIR_INVENTORY
             SET SEATS_SOLD = SEATS_SOLD + :AIR-PARTY-SIZE,
                 VERSION = VERSION + 1
             WHERE FLIGHT_ID = :WS-FLIGHT-ID AND CABIN = :AIR-CABIN
           END-EXEC.
       ISSUE-TICKETS.
           CALL "AIRTKT" USING AIR-PNR AIR-PARTY-SIZE AIR-RESPONSE.
       WRITE-OUTBOX-EVENT.
           EXEC SQL INSERT INTO AIR_EVENT_OUTBOX
             (EVENT_ID, AGGREGATE_ID, EVENT_TYPE, PAYLOAD, PUBLISHED)
             VALUES (:AIR-REQUEST-ID, :AIR-PNR,
                     'RESERVATION.CONFIRMED', :AIR-RESPONSE, 'N')
           END-EXEC.`},
{path:"src/AIRCANCL.cbl",type:"ONLINE",description:"Cancellation, ticket voiding, inventory release, refund calculation, and event creation.",code:`       IDENTIFICATION DIVISION.
       PROGRAM-ID. AIRCANCL.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       EXEC SQL INCLUDE SQLCA END-EXEC.
       COPY AIRCOM.
       01 WS-FLIGHT-ID                PIC S9(18) COMP-3.
       01 WS-ORIGINAL-TOTAL           PIC S9(7)V99 COMP-3.
       01 WS-CANCEL-FEE               PIC S9(5)V99 COMP-3 VALUE 75.
       01 WS-REFUND                   PIC S9(7)V99 COMP-3.
       PROCEDURE DIVISION.
       MAIN-PROCEDURE.
           EXEC SQL SELECT FLIGHT_ID, TOTAL_AMOUNT
             INTO :WS-FLIGHT-ID, :WS-ORIGINAL-TOTAL
             FROM AIR_RESERVATION
            WHERE PNR = :AIR-PNR AND STATUS = 'HK'
            FOR UPDATE OF STATUS
           END-EXEC
           IF SQLCODE = 100
              MOVE "C404" TO AIR-RESPONSE-CODE
              MOVE "ACTIVE RESERVATION NOT FOUND" TO AIR-RESPONSE-MESSAGE
              MOVE 8 TO AIR-RETURN-CODE GOBACK
           END-IF
           COMPUTE WS-REFUND = FUNCTION MAX
              (ZERO, WS-ORIGINAL-TOTAL - WS-CANCEL-FEE)
           EXEC SQL UPDATE AIR_RESERVATION SET STATUS = 'XX'
             WHERE PNR = :AIR-PNR END-EXEC
           EXEC SQL UPDATE AIR_INVENTORY
             SET SEATS_SOLD = SEATS_SOLD - :AIR-PARTY-SIZE,
                 VERSION = VERSION + 1
             WHERE FLIGHT_ID = :WS-FLIGHT-ID AND CABIN = :AIR-CABIN
           END-EXEC
           EXEC SQL UPDATE AIR_TICKET SET STATUS = 'VOID'
             WHERE PNR = :AIR-PNR END-EXEC
           CALL "AIRRFND" USING AIR-PNR WS-REFUND AIR-RESPONSE-CODE
           MOVE WS-REFUND TO AIR-TICKET-TOTAL
           MOVE "0000" TO AIR-RESPONSE-CODE
           MOVE "RESERVATION CANCELLED" TO AIR-RESPONSE-MESSAGE
           GOBACK.`},
{path:"src/AIRCHKIN.cbl",type:"ONLINE",description:"Check-in, seat assignment, document verification, and boarding-pass issuance.",code:`       IDENTIFICATION DIVISION.
       PROGRAM-ID. AIRCHKIN.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       EXEC SQL INCLUDE SQLCA END-EXEC.
       COPY AIRCOM.
       01 WS-SEAT-NUMBER              PIC X(4).
       01 WS-BOARDING-GROUP           PIC X.
       01 WS-DOCUMENT-VALID           PIC X VALUE "N".
       PROCEDURE DIVISION.
       MAIN-PROCEDURE.
           PERFORM VALIDATE-TRAVEL-DOCUMENTS
           IF WS-DOCUMENT-VALID NOT = "Y"
              MOVE "K102" TO AIR-RESPONSE-CODE
              MOVE "DOCUMENT CHECK REQUIRED" TO AIR-RESPONSE-MESSAGE
              MOVE 8 TO AIR-RETURN-CODE GOBACK
           END-IF
           EXEC SQL SELECT SEAT_NUMBER
             INTO :WS-SEAT-NUMBER
             FROM AIR_SEAT
            WHERE FLIGHT_ID = :AIR-FLIGHT-NUMBER
              AND CABIN = :AIR-CABIN AND STATUS = 'OPEN'
            ORDER BY SEAT_RANK FETCH FIRST 1 ROW ONLY
            FOR UPDATE OF STATUS
           END-EXEC
           IF SQLCODE NOT = ZERO
              MOVE "K201" TO AIR-RESPONSE-CODE
              MOVE "NO ASSIGNABLE SEAT" TO AIR-RESPONSE-MESSAGE
              MOVE 8 TO AIR-RETURN-CODE GOBACK
           END-IF
           EXEC SQL UPDATE AIR_SEAT SET STATUS = 'ASSIGNED', PNR = :AIR-PNR
             WHERE FLIGHT_ID = :AIR-FLIGHT-NUMBER
               AND SEAT_NUMBER = :WS-SEAT-NUMBER
           END-EXEC
           EVALUATE AIR-CABIN
              WHEN "J" MOVE "1" TO WS-BOARDING-GROUP
              WHEN "W" MOVE "2" TO WS-BOARDING-GROUP
              WHEN OTHER MOVE "4" TO WS-BOARDING-GROUP
           END-EVALUATE
           EXEC SQL UPDATE AIR_RESERVATION SET STATUS = 'CK'
             WHERE PNR = :AIR-PNR END-EXEC
           MOVE "0000" TO AIR-RESPONSE-CODE
           STRING "CHECKED IN - SEAT " WS-SEAT-NUMBER
             " GROUP " WS-BOARDING-GROUP
             DELIMITED BY SIZE INTO AIR-RESPONSE-MESSAGE END-STRING
           GOBACK.
       VALIDATE-TRAVEL-DOCUMENTS.
           IF AIR-PASSENGER-ID(1) NOT = SPACES
              MOVE "Y" TO WS-DOCUMENT-VALID
           END-IF.`},
{path:"src/AIRPNR.cbl",type:"SERVICE",description:"Collision-resistant PNR generation with an unambiguous alphabet and database uniqueness check.",code:`       IDENTIFICATION DIVISION.
       PROGRAM-ID. AIRPNR.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-ALPHABET PIC X(32) VALUE "23456789ABCDEFGHJKLMNPQRSTUVWXYZ".
       01 WS-HASH PIC 9(9) COMP VALUE ZERO.
       01 WS-IDX PIC 99 COMP.
       01 WS-POS PIC 99 COMP.
       LINKAGE SECTION.
       01 LK-REQUEST-ID PIC X(26).
       01 LK-PNR PIC X(6).
       PROCEDURE DIVISION USING LK-REQUEST-ID LK-PNR.
           PERFORM VARYING WS-IDX FROM 1 BY 1 UNTIL WS-IDX > 26
              COMPUTE WS-HASH = FUNCTION MOD
                 ((WS-HASH * 31) + FUNCTION ORD(LK-REQUEST-ID(WS-IDX:1)),
                  1073741823)
           END-PERFORM
           PERFORM VARYING WS-IDX FROM 6 BY -1 UNTIL WS-IDX < 1
              COMPUTE WS-POS = FUNCTION MOD(WS-HASH, 32) + 1
              MOVE WS-ALPHABET(WS-POS:1) TO LK-PNR(WS-IDX:1)
              DIVIDE 32 INTO WS-HASH
           END-PERFORM
           GOBACK.`},
{path:"src/AIRTKT.cbl",type:"SERVICE",description:"Electronic ticket document issuance with check-digit calculation.",code:`       IDENTIFICATION DIVISION.
       PROGRAM-ID. AIRTKT.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-SEQUENCE PIC 9(10) COMP-3.
       01 WS-TICKET PIC X(13).
       01 WS-CHECK-DIGIT PIC 9.
       01 WS-IDX PIC 99 COMP.
       LINKAGE SECTION.
       01 LK-PNR PIC X(6).
       01 LK-PARTY-SIZE PIC 99.
       01 LK-RESPONSE PIC X(256).
       PROCEDURE DIVISION USING LK-PNR LK-PARTY-SIZE LK-RESPONSE.
           PERFORM VARYING WS-IDX FROM 1 BY 1
             UNTIL WS-IDX > LK-PARTY-SIZE
              EXEC SQL SELECT NEXT VALUE FOR AIR_TICKET_SEQ
                INTO :WS-SEQUENCE FROM SYSIBM.SYSDUMMY1 END-EXEC
              COMPUTE WS-CHECK-DIGIT = FUNCTION MOD(WS-SEQUENCE, 7)
              STRING "999" WS-SEQUENCE WS-CHECK-DIGIT
                DELIMITED BY SIZE INTO WS-TICKET END-STRING
              EXEC SQL INSERT INTO AIR_TICKET
                (TICKET_NUMBER, PNR, PASSENGER_SEQ, STATUS)
                VALUES (:WS-TICKET, :LK-PNR, :WS-IDX, 'OPEN')
              END-EXEC
           END-PERFORM
           GOBACK.`},
{path:"batch/AIRDEPRT.cbl",type:"BATCH",description:"Departure-control closeout: manifest, load counts, no-show release, and reconciliation.",code:`       IDENTIFICATION DIVISION.
       PROGRAM-ID. AIRDEPRT.
       ENVIRONMENT DIVISION.
       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
           SELECT MANIFEST-FILE ASSIGN TO MANIFEST
             ORGANIZATION IS SEQUENTIAL FILE STATUS IS WS-FILE-STATUS.
       DATA DIVISION.
       FILE SECTION.
       FD MANIFEST-FILE RECORDING MODE F.
       01 MANIFEST-RECORD PIC X(240).
       WORKING-STORAGE SECTION.
       01 WS-FILE-STATUS PIC XX.
       01 WS-BOOKED PIC 9(4) COMP VALUE ZERO.
       01 WS-CHECKED-IN PIC 9(4) COMP VALUE ZERO.
       01 WS-BOARDED PIC 9(4) COMP VALUE ZERO.
       01 WS-NO-SHOW PIC 9(4) COMP VALUE ZERO.
       01 WS-END PIC X VALUE "N".
          88 END-OF-DATA VALUE "Y".
       PROCEDURE DIVISION.
       MAIN-PROCEDURE.
           OPEN OUTPUT MANIFEST-FILE
           PERFORM OPEN-PASSENGER-CURSOR
           PERFORM UNTIL END-OF-DATA
              PERFORM FETCH-PASSENGER
              IF NOT END-OF-DATA PERFORM WRITE-MANIFEST-ROW END-IF
           END-PERFORM
           PERFORM CLOSE-PASSENGER-CURSOR
           COMPUTE WS-NO-SHOW = WS-BOOKED - WS-CHECKED-IN
           PERFORM RELEASE-NO-SHOW-SEATS
           PERFORM WRITE-CONTROL-TOTALS
           CLOSE MANIFEST-FILE
           IF WS-FILE-STATUS NOT = "00" MOVE 12 TO RETURN-CODE END-IF
           STOP RUN.
       WRITE-CONTROL-TOTALS.
           DISPLAY "BOOKED=" WS-BOOKED
             " CHECKED-IN=" WS-CHECKED-IN
             " BOARDED=" WS-BOARDED
             " NO-SHOW=" WS-NO-SHOW.`},
{path:"db/schema.sql",type:"DB2",description:"Core DB2 tables, integrity constraints, indexes, temporal columns, and outbox.",code:`CREATE TABLE AIR_FLIGHT (
  FLIGHT_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CARRIER CHAR(3) NOT NULL, FLIGHT_NUMBER DECIMAL(4) NOT NULL,
  DEPARTURE_DATE DECIMAL(8) NOT NULL, ORIGIN CHAR(3) NOT NULL,
  DESTINATION CHAR(3) NOT NULL, DEPARTURE_TS TIMESTAMP NOT NULL,
  ARRIVAL_TS TIMESTAMP NOT NULL, STATUS CHAR(2) NOT NULL,
  UNIQUE (CARRIER, FLIGHT_NUMBER, DEPARTURE_DATE)
);
CREATE TABLE AIR_INVENTORY (
  FLIGHT_ID BIGINT NOT NULL REFERENCES AIR_FLIGHT,
  CABIN CHAR(1) NOT NULL, SEATS_TOTAL SMALLINT NOT NULL,
  SEATS_SOLD SMALLINT NOT NULL DEFAULT 0,
  SEATS_HELD SMALLINT NOT NULL DEFAULT 0,
  BASE_FARE DECIMAL(9,2) NOT NULL, VERSION INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (FLIGHT_ID, CABIN),
  CHECK (SEATS_SOLD + SEATS_HELD <= SEATS_TOTAL)
);
CREATE TABLE AIR_RESERVATION (
  PNR CHAR(6) PRIMARY KEY, FLIGHT_ID BIGINT NOT NULL REFERENCES AIR_FLIGHT,
  CABIN CHAR(1) NOT NULL, PARTY_SIZE SMALLINT NOT NULL,
  TOTAL_AMOUNT DECIMAL(9,2) NOT NULL, STATUS CHAR(2) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
  UPDATED_AT TIMESTAMP NOT NULL GENERATED ALWAYS FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP
);
CREATE TABLE AIR_PASSENGER (
  PNR CHAR(6) NOT NULL REFERENCES AIR_RESERVATION,
  PASSENGER_SEQ SMALLINT NOT NULL, FIRST_NAME VARCHAR(30) NOT NULL,
  LAST_NAME VARCHAR(30) NOT NULL, LOYALTY_NUMBER VARCHAR(16),
  PRIMARY KEY (PNR, PASSENGER_SEQ)
);
CREATE TABLE AIR_TICKET (
  TICKET_NUMBER CHAR(13) PRIMARY KEY, PNR CHAR(6) NOT NULL,
  PASSENGER_SEQ SMALLINT NOT NULL, STATUS CHAR(4) NOT NULL
);
CREATE TABLE AIR_COMMAND (
  IDEMPOTENCY_KEY CHAR(36) PRIMARY KEY, RESPONSE_CODE CHAR(4) NOT NULL,
  PNR CHAR(6), CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP
);
CREATE TABLE AIR_EVENT_OUTBOX (
  EVENT_ID CHAR(26) PRIMARY KEY, AGGREGATE_ID VARCHAR(32) NOT NULL,
  EVENT_TYPE VARCHAR(40) NOT NULL, PAYLOAD CLOB(64K) NOT NULL,
  PUBLISHED CHAR(1) NOT NULL DEFAULT 'N', CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP
);
CREATE INDEX AIR_OUTBOX_PUBLISH ON AIR_EVENT_OUTBOX (PUBLISHED, CREATED_AT);`},
{path:"jcl/AIRNIGHT.jcl",type:"JCL",description:"Nightly departure closeout, outbox publication, reconciliation, and conditional restart flow.",code:`//AIRNIGHT JOB (AIR),'NIGHT CLOSE',CLASS=A,MSGCLASS=X,
//             NOTIFY=&SYSUID,REGION=0M
//* RESTART=AIRNIGHT.RECON IS SAFE AFTER OUTBOX PUBLISH
//SORTIN   EXEC PGM=SORT
//SYSOUT   DD SYSOUT=*
//SORTIN   DD DSN=AIR.OPERATIONS.DEPARTURES,DISP=SHR
//SORTOUT  DD DSN=&&SORTED,DISP=(NEW,PASS),SPACE=(CYL,(10,5))
//SYSIN    DD *
  SORT FIELDS=(1,8,CH,A,9,4,ZD,A)
/*
//CLOSEOUT EXEC PGM=AIRDEPRT,COND=(4,LT)
//STEPLIB  DD DSN=AIR.PROD.LOAD,DISP=SHR
//INFILE   DD DSN=&&SORTED,DISP=(OLD,DELETE)
//MANIFEST DD DSN=AIR.MANIFEST(+1),DISP=(NEW,CATLG,DELETE),
//            SPACE=(CYL,(5,2)),DCB=(RECFM=FB,LRECL=240)
//SYSOUT   DD SYSOUT=*
//OUTBOX   EXEC PGM=AIROUTBX,COND=(4,LT)
//STEPLIB  DD DSN=AIR.PROD.LOAD,DISP=SHR
//SYSOUT   DD SYSOUT=*
//RECON    EXEC PGM=AIRRECON,COND=EVEN
//MANIFEST DD DSN=AIR.MANIFEST(+1),DISP=SHR
//CONTROL  DD DSN=AIR.CONTROL.TOTALS,DISP=SHR
//SYSOUT   DD SYSOUT=*`},
{path:"cics/definitions.txt",type:"CICS",description:"Transaction, program, and resource definitions for the online region.",code:`DEFINE TRANSACTION(AIR1) GROUP(AIRPROD) PROGRAM(AIRROUTE)
       DESCRIPTION(AIRLINE API ROUTER) TWASIZE(4096) STATUS(ENABLED)
DEFINE PROGRAM(AIRROUTE) GROUP(AIRPROD) LANGUAGE(COBOL)
       DATALOCATION(ANY) EXECKEY(CICS) CONCURRENCY(THREADSAFE)
DEFINE PROGRAM(AIRSRCH)  GROUP(AIRPROD) LANGUAGE(COBOL) CONCURRENCY(THREADSAFE)
DEFINE PROGRAM(AIRBOOK)  GROUP(AIRPROD) LANGUAGE(COBOL) CONCURRENCY(THREADSAFE)
DEFINE PROGRAM(AIRCANCL) GROUP(AIRPROD) LANGUAGE(COBOL) CONCURRENCY(THREADSAFE)
DEFINE PROGRAM(AIRCHKIN) GROUP(AIRPROD) LANGUAGE(COBOL) CONCURRENCY(THREADSAFE)
DEFINE PROGRAM(AIRPNR)   GROUP(AIRPROD) LANGUAGE(COBOL) CONCURRENCY(THREADSAFE)
DEFINE PROGRAM(AIRTKT)   GROUP(AIRPROD) LANGUAGE(COBOL) CONCURRENCY(THREADSAFE)
DEFINE URIMAP(AIRAPI) GROUP(AIRPROD) USAGE(SERVER) SCHEME(HTTPS)
       HOST(*) PATH(/v1/airline/*) TRANSACTION(AIR1) STATUS(ENABLED)
INSTALL GROUP(AIRPROD)`},
{path:"tests/AIRBOOKT.cbl",type:"TEST",description:"Table-driven booking tests covering success, capacity, duplicate commands, and boundary cases.",code:`       IDENTIFICATION DIVISION.
       PROGRAM-ID. AIRBOOKT.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       COPY AIRCOM.
       01 TEST-COUNT PIC 99 VALUE ZERO.
       01 FAILURE-COUNT PIC 99 VALUE ZERO.
       01 TEST-CASES.
          05 TEST-CASE OCCURS 5 TIMES.
             10 T-PARTY PIC 99.
             10 T-SEATS PIC 99.
             10 T-EXPECTED PIC X(4).
       PROCEDURE DIVISION.
           MOVE 1 TO T-PARTY(1) MOVE 9 TO T-SEATS(1) MOVE "0000" TO T-EXPECTED(1)
           MOVE 9 TO T-PARTY(2) MOVE 9 TO T-SEATS(2) MOVE "0000" TO T-EXPECTED(2)
           MOVE 3 TO T-PARTY(3) MOVE 2 TO T-SEATS(3) MOVE "A101" TO T-EXPECTED(3)
           MOVE 0 TO T-PARTY(4) MOVE 9 TO T-SEATS(4) MOVE "E003" TO T-EXPECTED(4)
           MOVE 10 TO T-PARTY(5) MOVE 20 TO T-SEATS(5) MOVE "E003" TO T-EXPECTED(5)
           PERFORM VARYING TEST-COUNT FROM 1 BY 1 UNTIL TEST-COUNT > 5
              MOVE T-PARTY(TEST-COUNT) TO AIR-PARTY-SIZE
              CALL "AIRBOOK" USING AIR-REQUEST AIR-RESPONSE
              IF AIR-RESPONSE-CODE NOT = T-EXPECTED(TEST-COUNT)
                 ADD 1 TO FAILURE-COUNT
                 DISPLAY "FAIL CASE " TEST-COUNT
              END-IF
           END-PERFORM
           DISPLAY "TESTS=5 FAILURES=" FAILURE-COUNT
           MOVE FAILURE-COUNT TO RETURN-CODE
           STOP RUN.`}
];
export const totalLines=airlineFiles.reduce((n,f)=>n+f.code.split("\n").length,0);
