import Link from "next/link";

const notes: Record<string, { summary: string; syntax: string; example: string }> = {
  move: { summary: "Copies data from one field or literal into one or more receiving fields, converting representation when the descriptions differ.", syntax: "MOVE source TO destination-1 [destination-2 ...]", example: `MOVE "ACTIVE" TO WS-STATUS.\nMOVE WS-SUBTOTAL TO WS-TOTAL WS-DISPLAY-TOTAL.` },
  perform: { summary: "Runs a paragraph, section, or inline block—once, repeatedly, or until a condition becomes true.", syntax: "PERFORM procedure-name [THRU end-name] [UNTIL condition]", example: `PERFORM READ-NEXT-RECORD\n   UNTIL END-OF-FILE = "Y".` },
  display: { summary: "Writes values to a terminal, system output, or a named destination.", syntax: "DISPLAY operand-1 [operand-2 ...]", example: `DISPLAY "CUSTOMER: " CUSTOMER-NAME.\nDISPLAY "BALANCE: " ACCOUNT-BALANCE.` },
};

export default async function ReferencePage({ params }: { params: Promise<{ verb: string }> }) { const { verb } = await params; const key = verb.toLowerCase(); const item = notes[key] ?? { summary: `${verb.toUpperCase()} is part of the COBOL language reference. This concise entry shows its core form and a practical usage pattern.`, syntax: `${verb.toUpperCase()} operand [phrase ...]`, example: `       ${verb.toUpperCase()} WS-SOURCE TO WS-RESULT.` }; return <div className="lesson-shell"><aside className="lesson-side"><Link href="/" className="brand"><span className="brand-mark">C</span><span>COBOL.campus</span></Link><small>LANGUAGE REFERENCE</small><nav><Link href="/reference/move">MOVE</Link><Link href="/reference/perform">PERFORM</Link><Link href="/reference/display">DISPLAY</Link><Link href="/#reference">← All statements</Link></nav></aside><main className="lesson-main"><Link className="back-mobile" href="/#reference">← REFERENCE</Link><div className="breadcrumb">REFERENCE / STATEMENT</div><h1>{verb.toUpperCase()}</h1><p className="lead">{item.summary}</p><div className="lesson-meta"><span>ISO COBOL</span><span>STATEMENT</span></div><article className="article"><h2>Syntax</h2><pre className="code-block"><code>{item.syntax}</code></pre><h2>Example</h2><pre className="code-block"><code>{item.example}</code></pre><div className="callout"><b>GOOD PRACTICE</b><br />Use explicit scope terminators such as END-IF and END-PERFORM. They make maintenance safer when logic changes.</div><h2>What to watch for</h2><p>Field size, category, sign, and decimal placement affect the result. Compile with warnings enabled and test boundary values whenever data moves between unlike descriptions.</p></article><div className="lesson-next"><span>Continue exploring the language.</span><Link href="/reference/perform">Next entry →</Link></div></main></div>; }
